export let menus = {
    START: 'START',
    MNEMONICS: 'MNEMONICS',
    BACKUP: 'BACKUP',
    CREATE_PASSWORD: 'CREATE_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    ENTER_PASSWORD: 'ENTER_PASSWORD',
    PASSWORD_CREATED: 'PASSWORD_CREATED',
    MAIN: 'MAIN',
    ABOUT: 'ABOUT',
    IMPORT: 'IMPORT'

};
export let signals = {
    MNEMONIC_WORDS: 'MNEMONIC_WORDS',
    BACKUP: 'BACKUP',
    CREATE_PASSWORD: 'CREATE_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    ENTER_PASSWORD: 'ENTER_PASSWORD',
    PASSWORD_CREATED: 'PASSWORD_CREATED',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    PASSWORD_ENTERED: 'PASSWORD_ENTERED',
    LOAD_MAIN: 'LOAD_MAIN',
    LOAD_START: 'LOAD_START',
    SWITCH_MENU_PANEL: 'SWITCH_MENU_PANEL',
    ABOUT: 'ABOUT',
    IMPORT: 'IMPORT'
};