export let menus = {
    START: 'START',
    MNEMONICS: 'MNEMONICS',
    BACKUP: 'BACKUP',
    CREATE_PASSWORD: 'CREATE_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    ENTER_PASSWORD: 'ENTER_PASSWORD',
    PASSWORD_CREATED: 'PASSWORD_CREATED',
    MAIN: 'MAIN',
    ABOUT: 'ABOUT',
    IMPORT: 'IMPORT',
    TRANSACTIONS: 'TRANSACTIONS'

};
export let signals = {
    LOAD_BACKUP: 'LOAD_BACKUP',
    LOAD_MAIN: 'LOAD_MAIN',
    LOAD_START: 'LOAD_START',
    LOAD_ABOUT: 'LOAD_ABOUT',
    LOAD_IMPORT: 'LOAD_IMPORT',
    LOAD_TRANSACTIONS: 'LOAD_TRANSACTIONS',
    MNEMONIC_WORDS: 'MNEMONIC_WORDS',
    CREATE_PASSWORD: 'CREATE_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    ENTER_PASSWORD: 'ENTER_PASSWORD',
    PASSWORD_CREATED: 'PASSWORD_CREATED',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    PASSWORD_ENTERED: 'PASSWORD_ENTERED',
    SWITCH_MENU_PANEL: 'SWITCH_MENU_PANEL',
};